### ISSUE TITLE
Typescript seems to be required

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/eslint-config#312]
Got this error when upgrading this config in a client project. It's complaining about not having Typescript installed, even though that project doesn't use Typescript.

```
> eslint . --ext .js

Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin '@cloudfour' declared in '.eslintrc.yaml': Cannot find module 'typescript'
Require stack:
- /path/to/project/node_modules/@typescript-eslint/eslint-plugin/dist/util/astUtils.js
- /path/to/project/node_modules/@typescript-eslint/eslint-plugin/dist/util/index.js
- /path/to/project/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js
- /path/to/project/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /path/to/project/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /path/to/project/node_modules/@cloudfour/eslint-plugin/src/rules.js
- /path/to/project/node_modules/@cloudfour/eslint-plugin/index.js
- /path/to/project/node_modules/@eslint/eslintrc/lib/config-array-factory.js
- /path/to/project/node_modules/@eslint/eslintrc/lib/index.js
- /path/to/project/node_modules/eslint/lib/cli-engine/cli-engine.js
- /path/to/project/node_modules/eslint/lib/eslint/eslint.js
- /path/to/project/node_modules/eslint/lib/eslint/index.js
- /path/to/project/node_modules/eslint/lib/cli.js
- /path/to/project/node_modules/eslint/bin/eslint.js
Referenced from: /path/to/project/.eslintrc.yaml
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:927:15)
    at Function.Module._load (node:internal/modules/cjs/loader:772:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/path/to/project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/path/to/project/node_modules/@typescript-eslint/eslint-plugin/dist/util/astUtils.js:27:25)
    at Module._compile (/path/to/project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1124:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:816:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
ERROR: "check-lint:js" exited with 2.
```

Here's their ESLint config:

```yaml
env:
  jest/globals: true
extends: plugin:@cloudfour/recommended
plugins:
  - jest
rules:
  "@cloudfour/no-param-reassign": off
  "@cloudfour/node/no-unpublished-import": off
  no-new: off
  "@cloudfour/node/no-missing-import": off #chokes on our dynamic import paths
  "@cloudfour/unicorn/prefer-node-protocol": off #causing test failures
```

If Typescript is a requirement, we should document that and set it as a dependency (peer dependency?).

Or, better yet, change things so it's not required on projects that don't use Typescript.
